🔀 :: (#6) Auth
2023-kbc-iuc/BackOffice pull request #10
Opened 2023-04-18 09:01 UTC by rlawnsgh714

close #6

2023-04-18 09:19 UTC, ericlee05 commented on src/main/java/kr/sanhak/backoffice/domain/admin/service/AdminService.java
> +    @Transactional
readonly=true 부탁드립니당

2023-04-18 09:19 UTC, ericlee05 commented on src/main/java/kr/sanhak/backoffice/global/lib/Encode.java
> +public class Encode {
`KeyEncoder`로 이름을 바꾸는 것도 좋을거 같아요

2023-04-18 09:19 UTC, ericlee05 commented on src/main/java/kr/sanhak/backoffice/global/properties/JwtProperties.java
> +
공백 제거해주세여

2023-04-18 09:19 UTC, ericlee05 commented on src/main/java/kr/sanhak/backoffice/global/security/SecurityConfiguration.java
> +                .sessionManagement()
`sessionManagement()` 호출이 2개 있는 거 같아요..!

2023-04-18 09:19 UTC, ericlee05 commented on src/main/java/kr/sanhak/backoffice/global/security/filter/ExceptionFilter.java
> +public class ExceptionFilter extends OncePerRequestFilter {
TODO: 제거

2023-04-18 09:19 UTC, ericlee05 commented on src/main/java/kr/sanhak/backoffice/global/security/filter/FilterConfig.java
> +    public void configure(HttpSecurity builder) {
ExceptionFilter가 사라질 예정이니, SecurityConfiguration이랑 FilterConfiguration이랑 합치는 게 좋을 거 같아요

2023-04-18 11:29 UTC, ericlee05 approved these changes
수고하셨습니당 👏

2023-04-25 08:23 UTC, iqpizza6349 requested changes
수고하셨습니다. merge 가 눈 앞(👀 🗻) 입니다!  끝까지 열심히 해봅시다!

2023-04-25 08:23 UTC, iqpizza6349 commented on src/main/java/kr/sanhak/backoffice/global/security/principle/AuthDetailsService.java
> +    public UserDetails loadUserByUsername(String id) throws UsernameNotFoundException {
저희 서비스 상 고정 아이디와 비밀번호를 사용하고 있습니다.
id 라는 변수명은 추후에 로직의 일부가 변경될 확장성을 열고 있는 변수명으로 오해받을 수 있습니다.
ignored 혹은 unused 로 변수명으로 작성하거나, 주석으로 사용되지 않을 매개변수임을 알려야할 것 같습니다.

2023-04-25 23:09 UTC, iqpizza6349 approved these changes
🎉수고하셨습니다!

2023-04-29 00:15 UTC, merged