🔀 :: (#1) 엔티티 작성
2023-kbc-iuc/BackOffice pull request #2
Opened 2023-04-10 05:10 UTC by ericlee05

close #1

2023-04-10 07:39 UTC, iqpizza6349 requested changes
🎉 수고하셨지만, 끝까지 화이팅입니다!

2023-04-10 07:39 UTC, iqpizza6349 commented on src/main/java/kr/sanhak/backoffice/domain/tag/entity/AddressState.java
> +    @Column(name = "short_name", unique = true, length = 10)
_(아마) 제가 실수 했을 겁니다._ 
index 칼럼을 `shortname`이라고 했지만, 실제 칼럼명은 `short_name` 이라고 지정되어서 매핑과정에서 예외가 발생할 것입니다.

2023-04-10 07:39 UTC, iqpizza6349 commented on src/main/java/kr/sanhak/backoffice/domain/company/entity/Company.java
> +    private LocalDate deletedAt;
ERD에는 `deleted_at` 칼럼 타입이 `date`가 아닌 `datetime` 타입입니다. 수정바랍니다.

2023-04-10 07:39 UTC, iqpizza6349 commented on src/main/java/kr/sanhak/backoffice/domain/company/entity/Company.java
> +    private Boolean isDeleted;
ERD에는 `is_deleted` 칼럼 타입이 일반적인 `tinyint` 타입이 아닌 `int(11)`로 작성되어 있습니다.
올바른 매핑을 위해서는 수정이 필요해보입니다.

2023-04-13 08:23 UTC, ericlee05 commented on src/main/java/kr/sanhak/backoffice/domain/tag/entity/AddressState.java
> +    @Column(name = "short_name", unique = true, length = 10)
DB 칼럼 네이밍을 따르면 `short_name`일테니, 그걸로 수정해놓겠습니다!

2023-04-13 08:27 UTC, ericlee05 commented on src/main/java/kr/sanhak/backoffice/domain/company/entity/Company.java
> +    private Boolean isDeleted;
앗 생각한 거와 달리 int였군요.. `columnDefinition` 옵션으로 타입 지정해 놓겠습니다.

2023-04-13 08:33 UTC, iqpizza6349 approved these changes
수고하셨습니다! 👍

2023-04-13 08:55 UTC, merged